import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const config = [
  ...nextVitals,
  ...nextTs,
  // types/database.ts is generated by `npm run gen:types`
  { ignores: [".next/**", "node_modules/**", "next-env.d.ts", "types/database.ts"] },
];

export default config;
