import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const config = [
  ...nextVitals,
  ...nextTs,
  // types/database.ts is generated by `npm run gen:types`
  // .claude/ holds agent tooling and git worktrees (each with its own .next build output)
  { ignores: [".next/**", "node_modules/**", ".claude/**", "next-env.d.ts", "types/database.ts"] },
];

export default config;
